spring:
  application:
    name: java-concurrency-scanner
  
  # Disable OpenAI autoconfiguration
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.openai.OpenAiAutoConfiguration
  
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          model: claude-3-sonnet-20240229
          temperature: 0.1
          max-tokens: 2000

logging:
  level:
    com.example.scanner: INFO
    org.springframework.ai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: scanner.log

management:
  endpoints:
    web:
      exposure:
        include: health,info
